### ISSUE TITLE
Geç mi kaldım sayfası için bir öneri 

### ISSUE THREAD

**Issue by peyloride** [mrabdullahsahin/yolharitasi#39]
Nisan ayı gibi keşfettiğim ve keşfettiğimden beri ne zaman bu soruyu herhangi bir konu için kendime sorsam aklıma gelip bana umut ve de ilham veren bir görsel var. Bu sayfayı gördüğüm anda da aklımda hemen canlandı. Bence bu haliyle ya da metin halinde eklenebilir.
![gorsel](https://store.donanimhaber.com/a9/55/a5/a955a57537e93017874b6a90c65955f1.jpg)

**Comment by mrabdullahsahin** [comment]
Katınız için teşekkür ederim. Bu içeriği direk eklemekten ziyade [bu](https://blog.adioma.com/late-bloomers-people-who-succeeded-infographic/) tarz bir içeriği eklemek daha faydalı olur diye düşünüyorum

**Comment by peyloride** [comment]
Anlıyorum, nazik cevabınız için teşekkürler. Bahsettiğiniz içerik de benzer düşüncede fakat benim paylaştığımdaki gibi felsefik bir anlam barındırmıyor bence, o yüzden kağıt üstündeki istatistiklerden ibaretler benim için. Ancak yine de belirli bir seviyede barındırmak ve bir düzeni korumak adına bahsettiğiniz tarzda bir içerik düşünmenizi anlayabiliyorum. Dolayısıyla bu iş kaydını kapatıyorum, güzel bir işe girişmişsiniz, teşekkür ederim.
